actions: !!set
  a: null
  b: null
  c: null
  cinque: null
  d: null
  due: null
  e: null
  f: null
  g: null
  h: null
  i: null
  j: null
  k: null
  l: null
  m: null
  n: null
  nove: null
  o: null
  otto: null
  p: null
  q: null
  quattro: null
  r: null
  s: null
  sei: null
  sette: null
  t: null
  tre: null
  u: null
  uno: null
  v: null
  w: null
  zero: null
counter:
  a: 100
  b: 100
  c: 100
  cinque: 100
  d: 100
  due: 100
  e: 100
  f: 100
  g: 100
  h: 100
  i: 100
  j: 100
  k: 100
  l: 100
  m: 100
  n: 100
  nove: 100
  o: 100
  otto: 100
  p: 100
  q: 100
  quattro: 100
  r: 100
  s: 100
  sei: 100
  sette: 100
  t: 100
  tre: 100
  u: 100
  uno: 100
  v: 100
  w: 100
  zero: 100
