YAMLFILE = "settings.yaml"  # actions: !!set { }   counter: { }
KEYPOINTS_FOLDER = "./dataset/keypoints"
VIDEOS_FOLDER = "./dataset/videos"
MODELS_FOLDER = "./models"
TRAINING_FOLDER = "./training"
DATASET_FOLDER = "./dataset"
BACKUP_FOLDER = "./backup"
LOGS_FOLDER = "logs"
SEQUENCE_LENGTH = 10
NUM_FRAME = 30
