actions: !!set
  I_me: null
  a: null
  accident: null
  b: null
  bed: null
  before: null
  book: null
  c: null
  candy: null
  cinque: null
  computer: null
  cool: null
  d: null
  deaf: null
  drink: null
  due: null
  e: null
  f: null
  g: null
  go: null
  h: null
  hello: null
  help: null
  i: null
  i_love_you: null
  j: null
  k: null
  l: null
  m: null
  n: null
  name: null
  'no': null
  nove: null
  o: null
  otto: null
  p: null
  q: null
  quattro: null
  r: null
  s: null
  see you later: null
  sei: null
  sette: null
  t: null
  tall: null
  thin: null
  trade: null
  tre: null
  u: null
  uno: null
  v: null
  w: null
  who: null
  x: null
  y: null
  'yes': null
  z: null
  zero: null
counter:
  I_me: 100
  a: 100
  accident: 11
  b: 100
  bed: 82
  before: 12
  book: 80
  c: 100
  candy: 42
  cinque: 100
  computer: 34
  cool: 43
  d: 100
  deaf: 61
  drink: 72
  due: 100
  e: 100
  f: 100
  g: 100
  go: 15
  h: 100
  hello: 100
  help: 64
  i: 100
  i_love_you: 76
  j: 100
  k: 100
  l: 100
  m: 100
  n: 100
  name: 101
  'no': 100
  nove: 100
  o: 100
  otto: 100
  p: 100
  q: 100
  quattro: 100
  r: 100
  s: 100
  see you later: 101
  sei: 100
  sette: 100
  t: 100
  tall: 13
  thin: 16
  trade: 44
  tre: 100
  u: 100
  uno: 100
  v: 100
  w: 100
  who: 54
  x: 100
  y: 100
  'yes': 100
  z: 100
  zero: 100
